site_name: MusikCity
repo_url: https://github.com/Interacao-Humano-Computador/2021.1-MusikCity
repo_name: ""

theme:
  name: material
  language: "pt"
  logo: ""
  favicon: ""
  icon:
    repo: fontawesome/brands/github

extra_css:
  - stylesheets/extra.css

nav:
  - Inicio: index.md
  - Planejamento: planejamento.md
  - Perfil de usuario:
    - Perfil de usuario: perfil.md
    - Personas: personas.md
  - Análise de Requisitos:
    - Analise de Tarefas: analise.md
    - Guia de Estilo: guiaDeEstilo.md 
    - Metas de Usabilidade: usabilidade.md
    - Principios Gerais do Projeto: principios.md
  - Storyboard:
    - Storyboard: storyboard.md
    - Planejamento Avaliação: planejamentoSt.md
  - Protótipo de Papel:
    - Planejamento da Avaliação do Protótipo de Papel: planejamentoPapel.md
  - Apresentação:
    - Apresentação 1: apresentacao1.md
    - Apresentação 2: apresentacao2.md
    - Apresentação 3: apresentacao3.md
    - Apresentação 4: apresentacao4.md

plugins:
  - mkdocs-video
