site_name: MusikCity
repo_url: https://github.com/Interacao-Humano-Computador/2021.1-MusikCity
repo_name: ''

theme:
  name: material
  language: 'pt'
  logo: ''
  favicon: ''
  icon:
    repo: fontawesome/brands/github

extra_css:
  - stylesheets/extra.css

nav:
  - Inicio: index.md
  - Planejamento: planejamento.md      
  - Análise de Requisitos:
      - Analise de Tarefas: analise.md
      - Guia de Estilo: guiaDeEstilo.md
      - Metas de Usabilidade: usabilidade.md
      - Perfil de usuario: personas.md
      - Principios Gerais do Projeto: principios.md
  - Design, Avaliação e Desenvolvimento:
      - Nivel 1:
          - Storyboards:
              - Storyboard: storyboard.md
              - Planejamento Avaliação: planejamentoSt.md
          - Analise de Tarefas:
              - Planejamento da Avaliação da Análise de Tarefas: planejamentoanalise.md
              - Resultados da Avaliação da Análise de Tarefas: resultadosanalise.md
      - Nivel 2:
          - Protótipo de Papel:
              - Planejamento da Avaliação do Protótipo de Papel: planejamentoPapel.md
              - Relato da Avaliação do Protótipo de Papel: RelatoPapel.md
      - Nivel 3:
          - Prototipo de Alta Fidelidade:
              - Planejamento da Avaliação do Protótipo de Alta fidelidade: planejamentoAF.md
  - Verificação dos Artefatos:
      - Análise de Requisitos: VerAnaliseReq.md
      - Guia de Estilo: VerGuidadeEstilo.md
      - Metas de usabilidade: VerMetas.md
      - Perfil do Usuário: VerPerfil.md
      - Princípios Gerais do Projeto: VerPrincipios.md
      - Storyboards: VerStoryboards.md
      - Planejamento Avaliação: VerPlanStory.md
  - Apresentação:
      - Apresentação 1: apresentacao1.md
      - Apresentação 2: apresentacao2.md
      - Apresentação 3: apresentacao3.md
      - Apresentação 4: apresentacao4.md

plugins:
  - mkdocs-video
